project:
  type: book
  output-dir: _book


book:
  title: "Research Project on SSAO Extraction and Enzyme Kinetics"
  author: "Prasaath Sastha Kuppan Ravi"
  reader-mode: true
  cover-image: cover.png
  page-footer: 
    left: Research project by <a href=https://prasaath-sastha.github.io/>Prasaath Sastha Kuppan Ravi</a>
    right: This book was built with <a href="https://quarto.org/">Quarto</a>.         
  favicon: logo.png
  site-url: "https://prasaath.quarto.pub/msc-research-project/"
  repo-url: https://github.com/PSArchitect0/MSc-Project/
  chapters:
    - index.qmd
    - intro.qmd
    - aims_and_objective.qmd
    - materials_and_methods.qmd
    - results.qmd
    - discussion.qmd
    - Limitations and future directions.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    css: styles.css
    theme: cosmo
    
    
website:
  open-graph: true
  site-url: "https://prasaath.quarto.pub/msc-research-project/"
  
author-meta: "Prasaath Sastha Kuppan Ravi"
callout-appearance: simple

editor: visual

